### ISSUE TITLE
LGTM.com - false positive - C++

### ISSUE THREAD

**Issue by AlexTereshenkov** [Semmle/ql#2046] opened 2019-09-27 12:54 UTC
**Description of the false positive**

Possible C++ false positive handling loop iteration variable.

This just started warning in the last day or two and the relevant code has not changed in some time so I suspect this is a recent regression in lgtm.

```
for(size_t i = 2; i != 64; i += 2)
  {
   ...
   }
```

Triggers `“Comparison is always true because i <= 2.”`

The variable `i` is incremented, so something doesn't look right.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/randombit/botan/snapshot/ef450671dd03cb1a44e889c4f33c717ec9ec206d/files/src/cli/speed.cpp?sort=name&dir=ASC&mode=heatmap#x779676b5d4d25d17:1

**Comment by randombit** [comment] 2019-09-27 13:52
This may be the same issue as #2029

**Comment by geoffw0** [comment] 2019-11-14 16:00
This also looks similar to https://discuss.lgtm.com/t/a-c-false-positive-in-my-project/1997 (https://jira.semmle.com/browse/CPP-383), which was worked around but I'm not sure if it's received a complete fix yet.  The essence of the problem is that the control flow graph through the loop body is broken such that we mistakenly believe a second loop iteration is impossible to reach.

**Comment by jbj** [comment] 2019-11-15 12:26
I agree these issues are likely to have the same root cause, and the workaround we implemented is likely to work for both projects. There are currently no alerts on randombit/botan.

I'll close this issue. Feel free to reopen if the false positive is still visible somewhere.

**Closed by jbj** 2019-11-15 12:26 UTC
Labels: C++, false-positive
