### ISSUE TITLE
LGTM.com - pointless-comparison FP on Wireshark

### ISSUE THREAD

**Issue by rknall** [Semmle/ql#2333] opened 2019-11-14 22:04 UTC
**Description of the false positive**

Both reported incidents are wrong, as the corresponding value is being set during a prefaced if-condition

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/wireshark/wireshark/latest/files/ui/qt/models/profile_model.cpp?sort=name&dir=ASC&mode=heatmap#V971

**Comment by jbj** [comment] 2019-11-15 12:54
I've done some initial investigation, and I'm quite confident that this FP is caused by #2077. There is no longer a control-flow path from `created++` to `created > 0` in that function. I'll see what I can do to fix it.

**Comment by jbj** [comment] 2019-11-15 13:58
In trying to reproduce this problem with a qltest, my best reproduction attempts give an "Unknown label" error on trap import. This means that we've somehow hit a corner case that the extractor doesn't handle right. I can't say if the error is the underlying cause of the reported false positive, but it's currently preventing me from investigating further because it's fatal for qltest.

The unknown label error happens when there are two nested `for` loops without braces between them and the inner loop initializes a variable that needs a destructor call:

```cpp
struct ClassWithDestructor
{
    ~ClassWithDestructor();
};

void myFunction()
{
    for (;;)
        for (ClassWithDestructor finfo;;)
        {
        }
}
```

I get this fatal error during qltest trap import:
```
[ERROR] qt.cpp.[283cc4e0].trap (qt.cpp.283cc4e0_0.trap.tar.br) (tuple expr_ancestor([I@3a6c1f04,#108)): Unknown label #108
```

Note that we're not using the `expr_ancestor` table to build the CFG, so the missing entry in this table should not be the direct cause of the false positive.

@igfoo, can someone from the extractor team take over this ticket so we can get the trap output in good shape?

**Comment by jbj** [comment] 2019-11-20 13:31
The extractor fix has been merged, and I can confirm that it fixes this false positive. Thanks, @igfoo!

The new extractor version should be deployed on lgtm.com in 2-3 weeks from now.

**Closed** 2019-11-20 14:54 UTC
Labels: C++, false-positive
