### ISSUE TITLE
LGTM.com - false positive Python __init_subclasses__

### ISSUE THREAD

**Issue by cdeil** [Semmle/ql#2253] opened 2019-11-04 20:27 UTC
This is a false positive:

https://lgtm.com/projects/g/gammapy/gammapy/snapshot/0801f741338ca656781d61682396086f4acefa57/files/gammapy/modeling/model.py?sort=name&dir=ASC&mode=heatmap#x98249dd4579c0864:1

It complains about `def __init_subclass__(cls, **kwargs):` saying
> Normal methods should have 'self', rather than 'cls', as their first parameter.

But `__init_subclass__` is a special method in Python, that gets passed the class and should take `cls` as argument, without having to add `@classmethod`.
See https://docs.python.org/3/reference/datamodel.html#customizing-class-creation

You probably have to special-case it in your linter.

**Comment by timhoffm** [comment] 2019-11-18 19:41
Duplicate of #2067.

**Closed** 2019-11-18 22:07 UTC
Labels: Python, false-positive
