### ISSUE TITLE
LGTM.com - false positive -  SLF4J API supports parametrization in the presence of an exception

### ISSUE THREAD

**Issue by bjhargrave** [Semmle/ql#2632] opened 2020-01-15 20:42 UTC
**Description of the false positive**

SLF4J support  supports parametrization in the presence of an exception. See http://www.slf4j.org/faq.html#paramException

So when there is a single excess argument and the argument is an exception, this should not trigger a false positive.

https://lgtm.com/projects/g/bndtools/bnd/snapshot/8bea51978e6f90242f83a4729ba13e25fa519e55/files/biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/RemotePostProcessor.java?sort=name&dir=ASC&mode=heatmap#xf92223ce4975d272:1

**Comment by aschackmull** [comment] 2020-01-16 13:56
That's weird - this case should already be accounted for.  I'm not sure what went wrong here as I can't seem to reproduce the issue, and the alert appears to be gone in the newest analyzed revision: https://lgtm.com/projects/g/bndtools/bnd/snapshot/52ee9cfc125b521d7fa2d6482312cbd8445aea52/files/biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/RemotePostProcessor.java?sort=name&dir=ASC&mode=heatmap#L131

**Comment by bjhargrave** [comment] 2020-01-16 14:04
Strange :-)

I'll close this issue then.

**Comment by bjhargrave** [comment] 2020-01-17 22:41
Another instance just popped up: https://lgtm.com/projects/g/bndtools/bnd/snapshot/c03d62adf17133af30f07cc25d142df849514993/files/biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/RemotePostProcessor.java?sort=name&dir=ASC&mode=heatmap#xf92223ce4975d272:1

**Comment by aschackmull** [comment] 2020-01-20 09:57
Debugging a bit yields this https://lgtm.com/query/6177137214305458072/, which shows that there must have been some problem during the extraction of the dependency containing `org.eclipse.aether.resolution.ArtifactResolutionException` as it doesn't have any supertypes (it should at the very least have `Object` as a supertype), and no supertypes mean that it isn't detecting as a subtype of `java.lang.Throwable`, so the query doesn't know that `e` is in fact an exception. @yo-h any ideas about the potential extraction problem here?

**Comment by yo-h** [comment] 2020-01-21 05:03
Thank you very much for reporting (and reopening) this issue. Indeed, the inheritance relation in the database does appear incomplete. We're investigating the root cause.

**Comment by yo-h** [comment] 2020-01-28 17:52
This issue exposed a subtle problem with our extraction process. A fix has been merged into our main development branch and is expected to be deployed within the next two weeks.

**Comment by yo-h** [comment] 2020-02-05 15:34
This change has now been deployed and we expect this issue to be resolved. If you notice any further issues of this nature, feel free to either reopen the issue or open a new one.

**Closed by yo-h** 2020-02-05 15:34 UTC
Labels: false-positive
