### ISSUE TITLE
LGTM.com - false positive - module imports itself

### ISSUE THREAD

**Issue by spapanik** [Semmle/ql#2781] opened 2020-02-06 14:01 UTC
In the module/\_\_init__.py when there is an import of the form `from module.submodule import *` it is getting marked as a `Module imports itself` error.

The reasoning is that "There is no need for a module to import itself." and an example of how to avoid it. In this case (which a valid use case, when you want to expose a specific API for the module) there are no alternatives.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/spapanik/pyrencode/snapshot/bf4f1509e20f7b476d54f209cccc38b4c15596cb/files/src/pyrencode/__init__.py?sort=name&dir=ASC&mode=heatmap#xbba2c982130e5e33:1

**Comment by tausbn** [comment] 2020-02-06 14:06
Thank you for your report. We are aware of this problem, and are working on a fix. 

As this is a duplicate of #2771, please refer to that issue for further information.

**Closed** 2020-02-06 16:12 UTC
Labels: Python, duplicate, false-positive
