### ISSUE TITLE
Alert suppression not working in multiple places

### ISSUE THREAD

**Issue by dgw** [Semmle/ql#2361] opened 2019-11-17 09:35 UTC
**Description of the issue**

It appears that at least some alert suppression comments in Python are currently broken.

After copying the rule names for the alerts I wanted to suppress into the files, following either the style shown in the documentation (`# lgtm[rule/name-here]`) or the style in the inline "hide this" box in an analysis (`# lgtm [rule/name-here]` — note the space), the alerts are **not** marked as resolved.

Both of these analyses show the problem in the same files, `root/sopel/module.py` and `root/sopel/irc/backends.py`.

https://lgtm.com/projects/g/sopel-irc/sopel/rev/pr-f1dc8343780163b970d236c6b467577051733383
https://lgtm.com/projects/g/sopel-irc/sopel/rev/pr-55e9c9f6cd358f40b5d2e0372c24e284c3cf6878

Either should have resulted in all of the following alerts being marked as resolved, unless I'm misunderstanding how alert suppression works.

https://lgtm.com/projects/g/sopel-irc/sopel/snapshot/182754526ebc14910cf4082e664542155d4460d9/files/sopel/irc/backends.py#xb8622514580c4fca:1
https://lgtm.com/projects/g/sopel-irc/sopel/snapshot/182754526ebc14910cf4082e664542155d4460d9/files/sopel/irc/backends.py#xb86225162297542f:1
https://lgtm.com/projects/g/sopel-irc/sopel/snapshot/182754526ebc14910cf4082e664542155d4460d9/files/sopel/module.py#x2e1276a8323e6dba:1
https://lgtm.com/projects/g/sopel-irc/sopel/snapshot/182754526ebc14910cf4082e664542155d4460d9/files/sopel/module.py#x5ac5294b0292d05f:1

**Comment by tausbn** [comment] 2019-11-18 12:18
By design, alert suppressions are not applied in pull requests (to prevent the case where a pull request introduces a bug, and also suppresses it at the same time). See https://lgtm.com/help/lgtm/automated-code-review-faqs#why-automated-code-review-reports-misses-alert for more info.

I see nothing wrong with the way you have expressed the suppressions, so I would expect them to apply once the PR has been merged.

The UI for this could be better, stating that the alert in question _would_ be suppressed once the PR gets merged, which would hopefully be less confusing. I believe there are plans for such a change, but I'm afraid I don't have an ETA for this at the moment.

**Comment by dgw** [comment] 2019-11-18 19:32
Well that was a surprise hiding in the docs. Thought I'd read everything about PR analysis.

How long should it take for LGTM to analyze new revisions pushed to the default/`master` branch? The most recent revision listed in the [history](https://lgtm.com/projects/g/sopel-irc/sopel/history/) is from two days ago, though newer commits have been pushed since (both yesterday and today).

**Closed** 2019-11-19 09:59 UTC
Labels: Python, question

**Comment by dgw** [comment] 2019-11-19 10:00
LGTM got caught up, and is now showing only the one issue for which I didn't quite have a fix ready. We're all set, thanks!

**Comment by tausbn** [comment] 2019-11-19 10:11
Excellent! As for your question, LGTM _should_ check for new commits roughly once per day, but I guess it may occasionally take a bit longer to do so.
